### ISSUE TITLE
Questions about K values

### ISSUE THREAD

**Issue by weiwFu** [bcm-uga/pcadapt#63]
Hi, I have two questions about pcadapt. 

One is that the Scree plot can determine the best choice of K. Can I output the optimal K value directly with R package because I want to call this parameter directly to the next program.

Another problem is that if the optimal k = 2, the difference between the two groups can be calculated, which is similar to the algorithm of FST. 

But when the optimal k = 1, does it mean that pcadapt will not be used any more? It can not calculate the selection signal of single population like other software, such as Pi, Hp, CLR, etc. 

When optimal k > 2, it means that there are three or more groups, so how to distinguish the calculated selection signals belong to which group? 

Thank you in advance.

Weiwei Fu

**Comment by privefl** [comment]
What do you mean by "the best choice of K from the R package"? This choice is made by the user, based on looking at the screeplot and PC scores.

I guess it is more the case K=1 that corresponds to Fst. Because with K PCs, you can separate K+1 populations.

pcadapt is really useful when K>1 (i.e. there are more than 2 populations)
I'm not sure this is designed to look at each pair of population (although you could do this by first filtering the bed/bim/fam files with e.g. PLINK and running each population pairs separetely -> I think this was discussed in another issue here).

**Comment by weiwFu** [comment]
Thank you very much for your reply. I want to get the optimal k directly. This is very useful for me to do batch operations and put this parameter directly to the next program.  Whether pcadapt can directly output the optimal K value to me, not in a graphic way? 

Also thank you for your reply to the selection signal. If I have one group, pcadapt would no longer apply?

If I have more than 2 populations, how do I distinguish which group (or more than one) is under selection.

If possible, can you give an example of the application of multi group selection signal, which will be very important and helpful for me to understand this software.

**Comment by privefl** [comment]
Estimating K programmatically can be tricky.

To apply pcadapt, you need population structure in your data (that will be captured via PCA).
You can find applications in the 2017 paper.

**Comment by ribaslej** [comment]
Hi all. My question is somewhat similar, so I didn't open a new topic.

I'm running RADseq analysis of a small rodent with samples throughout the distribution. I have 16 populations and 59 individuals, after previously filtering I got ~4K SNPs. PCA (PC1 and PC2) shows that populations are geographically structured, higher PCs also shows structured populations. I ran find.clusters (adegenet) and snmf (LEA) functions to explore clustering, getting K = 3, K = 16 (find.clusters) and K = 8 (snmf, which admits admixtured populations).

My question is about how many PCs to choose in pcadapt function. Although my VCF file was filtering used MAF = 0.05, I ran MAF = 0.1 in pcadapt to avoid detect outliers in only one population (I have populations distributed in three macroregions).

I think that values of 4, 7, 13 and 16 are acceptable.
![PCA](https://user-images.githubusercontent.com/60926164/110529959-a2698080-80f8-11eb-8bdc-330949eee9ba.png)
![screeplot](https://user-images.githubusercontent.com/60926164/110527781-21a98500-80f6-11eb-810d-8076af04b48a.png)
 
 For K = 4, I got 429 / 258 outliers (FDR = 0.05, without adjust/"holm" method) 
![qqplot K4](https://user-images.githubusercontent.com/60926164/110529001-7e596f80-80f7-11eb-8e23-7935ddd3e31f.png)
![stats distrib K4](https://user-images.githubusercontent.com/60926164/110529005-7ef20600-80f7-11eb-9e35-1cd4da551315.png)
![manhattan plot K4](https://user-images.githubusercontent.com/60926164/110529011-7f8a9c80-80f7-11eb-85c8-ec162b3b298a.png)

For K=7, i got 337 / 179 outliers (same parameters)
![qqplot K7](https://user-images.githubusercontent.com/60926164/110528917-6a157280-80f7-11eb-9e7b-8da45820a2d1.png)
![stats distrib K7](https://user-images.githubusercontent.com/60926164/110528925-6aae0900-80f7-11eb-8e73-d9fb66007c6f.png)
![manhattan plot K7](https://user-images.githubusercontent.com/60926164/110528930-6b469f80-80f7-11eb-9596-41d20939530a.png)

K = 13, I got 443 / 267 outliers
![stats distrib K13](https://user-images.githubusercontent.com/60926164/110529267-ced0cd00-80f7-11eb-9a1a-82c26c59b2bc.png)
![manhattan plot K13](https://user-images.githubusercontent.com/60926164/110529268-cf696380-80f7-11eb-8af3-e8d55c9cd42f.png),
![qqplot K13](https://user-images.githubusercontent.com/60926164/110529265-ce383680-80f7-11eb-8d48-00b1cf58024d.png)

and for K = 16, I got 627 / 429 outliers
![qqplot K16](https://user-images.githubusercontent.com/60926164/110529772-69311080-80f8-11eb-8a1b-f8fb2719ebe2.png)
![stat distrib K16](https://user-images.githubusercontent.com/60926164/110529775-69c9a700-80f8-11eb-99ee-c13d6c1c22be.png)
![manhattan plot K16](https://user-images.githubusercontent.com/60926164/110529778-6a623d80-80f8-11eb-9aea-1ba0705230a1.png)

Do you have any hints on choosing the value of K?

I also expect that distribution follow a hierarchical step in stones model, so I can have drift effect on SNPs related to local and I think that choosing a high value for K will increase confounding effects.

Finally, I also ran BayeScan analysis and only when considering K = 13 and K = 16 I found common SNPs in both methods (3 / 2 and 8 / 7, for K = 13 and K = 16 and without correction / "holm" method, respectively). 

Thank you if anyone could help.
Regards,
Luiz Eduardo

**Comment by privefl** [comment]
Choosing K is easy.
From the scree plot, I would probably choose 15. This should be a good enough starting value to look at PC scores.

Then, you need to look at the PC score around PC15, to see which are
- capturing population structure
- capturing artifacts such as LD
- just noise (just a circle)

Stop when you do not capture pop structure anymore.

**Comment by ribaslej** [comment]
Thank you for your Florian Privé, and sorry for the large pictures above.

I have investigated PC scores but signal is confusing, since for PC5 until PC10 populations start to grouping around center but still keeping individuals related. From PC13 and higher, the signal is lost.

Any way thank you again for helping, I will think more about your answer.

Regards,
 Luiz Eduardo

![PC5xPC6](https://user-images.githubusercontent.com/60926164/110542808-4d356b00-8108-11eb-9ebd-2271bb4c7fe6.png)
![PC7xPC8](https://user-images.githubusercontent.com/60926164/110543186-c3d26880-8108-11eb-816f-b20441ee7b86.png)
![PC9xPC10](https://user-images.githubusercontent.com/60926164/110542812-4e669800-8108-11eb-8a1b-031087467f68.png)
![PC11xPC12](https://user-images.githubusercontent.com/60926164/110542813-4e669800-8108-11eb-81cf-9c2e3a89a39d.png)
![PC13xPC14](https://user-images.githubusercontent.com/60926164/110542814-4eff2e80-8108-11eb-829e-6e759832ab3b.png)
![PC15xPC16](https://user-images.githubusercontent.com/60926164/110542818-4f97c500-8108-11eb-8f48-77dd9a947a97.png)

**Comment by privefl** [comment]
That's right.
It is harder to tell with just a few individuals in each population.

Then, based on the screeplot again, I would recommend to use 6 if you want to play it safe, and 15 otherwise.

**Comment by ribaslej** [comment]
Thank you for your time and answers!
