### ISSUE TITLE
Identifying snp positions of putatitively selected loci

### ISSUE THREAD

**Issue by jayyeam** [bcm-uga/pcadapt#80]
Hello, I successfully ran pcadapt using a bed file of my snp data, identifying putative loci under selection. After determining the number of outlier snps that surpass the cutoff, I was curious what the best method is to realign those snps back to my bed file so that I can identify the position of those snps and determine what genes they are involved in. Do you have any recommendations for the best approach to do this?

Thank you!

**Comment by privefl** [comment]
You should get results corresponding to variants in the .bim file, so yes.

**Comment by burbrink** [comment]
I have a similar question, using a VCF file. I don't see a way with these results to determine which SNP is associated with Pvalue etc. in the results. Do I just assume these are the same order as the VCF file? Any help would be appreciated.

Thanks.

Frank

**Comment by privefl** [comment]
VCF is not officially supported.
I would recommend to use PLINK to easily convert to bed/bim/fam (+ do a bit of QC at the same time).

**Comment by burbrink** [comment]
That’s odd, because on your vignette it says VCF is supported and my VCF reads in using read.pcadapt. Could you explain? Thanks.You should use the read.pcadapt function to convert your genotype file to the bed format, which is PLINK binary biallelic genotype table. read.pcadapt converts different types of files to the bed format and returns a character string containing the name of the converted file, which should be used as input for the pcadaptfunction. Supported formats are the following: “pcadapt”, “lfmm”, “vcf”, “bed”, “ped”, “pool”. pcadapt files should have individuals in columns, SNPs in lines, and missing values should be encoded by a single character (e.g. 9) different from 0, 1 or 2.

**Comment by privefl** [comment]
> `type`: A character string specifying the type of data to be converted from. Converters from ’vcf’ and ’ped’ formats are not maintained anymore; if you have any issue with those, please use PLINK >= 1.9 to convert them to the ’bed’ format.

**Comment by privefl** [comment]
https://github.com/bcm-uga/pcadapt/blob/master/R/pcadaptRead.R#L91
> warning("Converter vcf to pcadapt is deprecated. Please use PLINK for conversion to bed (and QC).")
